### ISSUE TITLE
Windows build help

### ISSUE THREAD

**Issue by TS440S** [esuldin/dump1090#1]
I would like to compile this on windows, I have linux but I'd also like to run it on windows. It would seem that Cmake can't find a C compiler or a CXX compiler. How would I go about installing this?

**Comment by esuldin** [comment]
CMake supports several generators on Windows, for example Visual Studio generator, MSYS Makefile generator and others. So, you can choose the preferable generator and install necessary software for it (Visual Studio, MSYS or other). Also please note, you need WinSDK to build dump1090 on Windows. I recommend to use Visual Studio 2019 Community edition. You need to install "Desktop development with C++" workload (it includes Microsoft C/C++ compiler and WinSDK) to build the program.
